import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CreditCard, Plus, Search } from "lucide-react";
import { useState, type FormEvent } from "react";
import { api, json, type PageData } from "../lib/api";
import { dateTime, money, yuanToCents } from "../lib/format";
import { Empty, LoadingPage, Message, Modal, PageHeader, Pagination, Spinner, StatusBadge } from "../components/ui";

interface Card { id: string; card_no: string; balance_cents: number; status: "ACTIVE" | "DISABLED"; remark: string; created_at: string }

export function AdminCardsPage() {
  const client = useQueryClient();
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [filter, setFilter] = useState(""); const [open, setOpen] = useState(false);
  const [cardNo, setCardNo] = useState(""); const [amount, setAmount] = useState(""); const [remark, setRemark] = useState("");
  const query = useQuery({ queryKey: ["admin-cards", page, filter], queryFn: () => api<PageData<Card>>(`/api/admin/cards?page=${page}${filter ? `&cardNo=${encodeURIComponent(filter)}` : ""}`) });
  const create = useMutation({ mutationFn: () => api("/api/admin/cards", json("POST", { cardNo, initialAmountCents: yuanToCents(amount), remark })), onSuccess: async () => { setOpen(false); setCardNo(""); setAmount(""); setRemark(""); await client.invalidateQueries({ queryKey: ["admin-cards"] }); await client.invalidateQueries({ queryKey: ["dashboard"] }); } });
  const toggle = useMutation({ mutationFn: (card: Card) => api(`/api/admin/cards/${card.id}/${card.status === "ACTIVE" ? "disable" : "enable"}`, json("POST")), onSuccess: () => client.invalidateQueries({ queryKey: ["admin-cards"] }) });
  const submitSearch = (e: FormEvent) => { e.preventDefault(); setPage(1); setFilter(search.trim()); };
  if (query.isLoading) return <LoadingPage />;
  return <><PageHeader title="卡号管理" description="创建、查询和启停卡号；卡号及历史流水不会被物理删除" action={<button className="btn-primary" onClick={() => setOpen(true)}><Plus className="size-4" />新增卡号</button>} /><div className="panel overflow-hidden"><form onSubmit={submitSearch} className="flex gap-3 border-b border-black/5 p-5"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 size-4 text-black/30" /><input className="input !h-10 pl-9 font-mono" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="按完整卡号搜索" /></div><button className="btn-secondary">查询</button>{filter && <button type="button" className="text-sm text-black/40" onClick={() => { setSearch(""); setFilter(""); }}>清除</button>}</form>{query.data?.items.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>卡号</th><th className="text-right!">当前金额</th><th>状态</th><th>创建时间</th><th>备注</th><th>操作</th></tr></thead><tbody>{query.data.items.map((card) => <tr key={card.id}><td className="font-mono font-semibold">{card.card_no}</td><td className="text-right! text-base font-bold tabular-nums">{money(card.balance_cents)}</td><td><StatusBadge active={card.status === "ACTIVE"} /></td><td className="whitespace-nowrap">{dateTime(card.created_at)}</td><td className="max-w-60 truncate">{card.remark || "—"}</td><td><button className={card.status === "ACTIVE" ? "btn-danger" : "btn-secondary !h-9"} disabled={toggle.isPending} onClick={() => toggle.mutate(card)}>{card.status === "ACTIVE" ? "禁用" : "启用"}</button></td></tr>)}</tbody></table></div> : <Empty text="暂无卡号" />}<Pagination page={page} totalPages={query.data?.totalPages ?? 0} onChange={setPage} /></div>
    <Modal open={open} title="新增卡号" onClose={() => setOpen(false)}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><div><label className="label">卡号</label><div className="relative"><CreditCard className="absolute left-3.5 top-3.5 size-4 text-black/30" /><input autoFocus className="input pl-10 font-mono uppercase" value={cardNo} onChange={(e) => setCardNo(e.target.value)} placeholder="例如 JM202608270001" /></div></div><div><label className="label">初始金额（元）</label><input className="input" inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="5000.00" /></div><div><label className="label">备注</label><textarea className="input !h-20 py-3" maxLength={500} value={remark} onChange={(e) => setRemark(e.target.value)} placeholder="选填" /></div>{create.error && <Message type="error">{create.error.message}</Message>}<div className="flex justify-end gap-3 pt-2"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>取消</button><button className="btn-primary" disabled={create.isPending || !/^[A-Za-z0-9_-]{3,64}$/.test(cardNo) || !yuanToCents(amount)}>{create.isPending ? <Spinner /> : "确认创建"}</button></div></form></Modal></>;
}
