import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { KeyRound, Plus, UserRound } from "lucide-react";
import { useState } from "react";
import { api, json, type PageData } from "../lib/api";
import { dateTime, money } from "../lib/format";
import { Empty, LoadingPage, Message, Modal, PageHeader, Pagination, Spinner, StatusBadge } from "../components/ui";

interface Account { id: string; username: string; display_name: string; status: "ACTIVE" | "DISABLED"; created_at: string; last_login_at: string | null; increase_cents: number; decrease_cents: number; transaction_count: number }

export function AdminUsersPage() {
  const client = useQueryClient(); const [page, setPage] = useState(1); const [mode, setMode] = useState<"create" | "edit" | "reset" | null>(null); const [selected, setSelected] = useState<Account | null>(null); const [username, setUsername] = useState(""); const [displayName, setDisplayName] = useState(""); const [password, setPassword] = useState("");
  const query = useQuery({ queryKey: ["admin-users", page], queryFn: () => api<PageData<Account>>(`/api/admin/users?page=${page}`) });
  const close = () => { setMode(null); setSelected(null); setUsername(""); setDisplayName(""); setPassword(""); mutate.reset(); };
  const mutate = useMutation({ mutationFn: () => mode === "create" ? api("/api/admin/users", json("POST", { username, displayName, password })) : mode === "edit" ? api(`/api/admin/users/${selected?.id}`, json("PUT", { username, displayName })) : api(`/api/admin/users/${selected?.id}/reset-password`, json("POST", { password })), onSuccess: async () => { close(); await client.invalidateQueries({ queryKey: ["admin-users"] }); } });
  const toggle = useMutation({ mutationFn: (account: Account) => api(`/api/admin/users/${account.id}/${account.status === "ACTIVE" ? "disable" : "enable"}`, json("POST")), onSuccess: () => client.invalidateQueries({ queryKey: ["admin-users"] }) });
  const edit = (account: Account) => { setSelected(account); setUsername(account.username); setDisplayName(account.display_name); setMode("edit"); };
  if (query.isLoading) return <LoadingPage />;
  return <><PageHeader title="子账号管理" description="创建、维护和查看子账号交易概况" action={<button className="btn-primary" onClick={() => setMode("create")}><Plus className="size-4" />创建子账号</button>} /><div className="panel overflow-hidden">{query.data?.items.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>账号</th><th>状态</th><th>交易概况</th><th>创建时间</th><th>最后登录</th><th>操作</th></tr></thead><tbody>{query.data.items.map((account) => <tr key={account.id}><td><div className="font-semibold">{account.display_name}</div><div className="mt-1 font-mono text-xs text-black/40">@{account.username}</div></td><td><StatusBadge active={account.status === "ACTIVE"} /></td><td><div className="text-xs"><span className="text-emerald-700">增 {money(account.increase_cents)}</span><span className="mx-2 text-black/15">/</span><span className="text-red-600">减 {money(account.decrease_cents)}</span></div><div className="mt-1 text-xs text-black/35">共 {account.transaction_count ?? 0} 笔</div></td><td>{dateTime(account.created_at)}</td><td>{dateTime(account.last_login_at)}</td><td><div className="flex gap-2"><button className="btn-secondary !h-9 !px-3" onClick={() => edit(account)}>编辑</button><button className="btn-secondary !h-9 !px-3" onClick={() => { setSelected(account); setMode("reset"); }}><KeyRound className="size-3.5" />重置密码</button><button className={account.status === "ACTIVE" ? "btn-danger" : "btn-secondary !h-9"} onClick={() => toggle.mutate(account)}>{account.status === "ACTIVE" ? "禁用" : "启用"}</button></div></td></tr>)}</tbody></table></div> : <Empty text="暂无子账号" />}<Pagination page={page} totalPages={query.data?.totalPages ?? 0} onChange={setPage} /></div>
    <Modal open={mode !== null} title={mode === "create" ? "创建子账号" : mode === "edit" ? "编辑子账号" : "重置密码"} onClose={close}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); mutate.mutate(); }}>{mode !== "reset" && <><div><label className="label">显示名称</label><div className="relative"><UserRound className="absolute left-3.5 top-3.5 size-4 text-black/30" /><input className="input pl-10" value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="例如：张三" /></div></div><div><label className="label">用户名</label><input className="input font-mono" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="zhangsan" /></div></>}{mode !== "edit" && <div><label className="label">{mode === "reset" ? `为 ${selected?.display_name} 设置新密码` : "初始密码"}</label><input type="password" autoComplete="new-password" className="input" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="至少 8 位" /></div>}{mode === "reset" && <p className="rounded-xl bg-wheat-50 p-3 text-xs leading-5 text-wheat-800">重置后，该账号的所有旧登录会话将立即失效。</p>}{mutate.error && <Message type="error">{mutate.error.message}</Message>}<div className="flex justify-end gap-3 pt-2"><button type="button" className="btn-secondary" onClick={close}>取消</button><button className="btn-primary" disabled={mutate.isPending || (mode !== "reset" && (!displayName.trim() || !/^[A-Za-z0-9_.-]{3,32}$/.test(username))) || (mode !== "edit" && password.length < 8)}>{mutate.isPending ? <Spinner /> : "确认"}</button></div></form></Modal></>;
}
