import { useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { KeyRound, ShieldCheck, UserRound } from "lucide-react";
import { useAuth } from "../auth";
import { Message, PageHeader, Spinner } from "../components/ui";
import { api, json } from "../lib/api";

export function ProfilePage() {
  const { user, refresh } = useAuth(); const navigate = useNavigate(); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (newPassword !== confirm) { setError("两次输入的新密码不一致"); return; } setLoading(true); try { await api("/api/auth/change-password", json("POST", { currentPassword, newPassword })); await refresh(); navigate("/login"); } catch (err) { setError(err instanceof Error ? err.message : "修改失败"); } finally { setLoading(false); } };
  return <><PageHeader title="个人中心" description="查看当前账号信息并维护登录密码" /><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div className="panel p-6"><div className="grid size-14 place-items-center rounded-2xl bg-wheat-100 text-wheat-800"><UserRound /></div><h2 className="mt-5 text-xl font-bold">{user?.displayName}</h2><p className="mt-1 font-mono text-sm text-black/40">@{user?.username}</p><div className="mt-6 flex items-center gap-2 border-t border-black/5 pt-5 text-sm text-black/50"><ShieldCheck className="size-4 text-emerald-600" />{user?.role === "SUPER_ADMIN" ? "超级管理员" : "子账号"}</div></div><div className="panel p-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-black/5"><KeyRound className="size-5" /></div><div><h2 className="font-bold">修改密码</h2><p className="mt-0.5 text-xs text-black/40">修改成功后所有设备将退出登录</p></div></div><form onSubmit={submit} className="mt-6 max-w-lg space-y-4"><div><label className="label">当前密码</label><input className="input" type="password" autoComplete="current-password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></div><div><label className="label">新密码</label><input className="input" type="password" autoComplete="new-password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} placeholder="至少 8 位" /></div><div><label className="label">确认新密码</label><input className="input" type="password" autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} /></div>{error && <Message type="error">{error}</Message>}<button className="btn-primary" disabled={loading || currentPassword.length < 8 || newPassword.length < 8 || confirm.length < 8}>{loading ? <Spinner /> : "保存新密码"}</button></form></div></div></>;
}
